### ISSUE TITLE
HTTPS Support

### ISSUE THREAD

**Issue by turtleslow** [boombatower/tumbleweed-cli#11]
Would be nice if tumbleweed-cli supported using https.  I modified my repositories to use https at some point and it took some time to figure out why tumbleweed-cli was not working correctly (I had forgotten about the modification).

I suppose it would make the code slightly more convoluted, but I would say the way to go about it is to check each repo whether it's using http or https and then stick to the protocol on a repo-by-repo basis.

I suppose it's debatable whether https is necessary for the repos, but I generally like to share as little info as possible with my ISP, public wifi, etc.

**Comment by turtleslow** [comment]
P.S.: thanks for creating tw-cli!!  It came in quite handy yesterday with some compatibility issues I'm having with the recent snapshots (graphics on kernel 5.1.x don't work for me ... had to go back to 5.0.x).

**Comment by boombatower** [comment]
#12
