### ISSUE TITLE
tumbleweed init uses hardcoded snapshot name instead of '$snapshotVersion' in .repo files

### ISSUE THREAD

**Issue by itaranto** [boombatower/tumbleweed-cli#13]
After running tumbleweed init, both repo-oss.repo have repo-non-oss.repo have:

name=openSUSE-Tumbleweed-Oss (<INITIAL_VERSION>)
name=openSUSE-Tumbleweed-Non-Oss (<INITIAL_VERSION>)

instead of:

name=openSUSE-Tumbleweed-Oss ($snapshotVersion)
name=openSUSE-Tumbleweed-Non-Oss ($snapshotVersion)

This makes difficult to check the current snapshot when using **zypper lr**.

**Comment by boombatower** [comment]
Hmm, I take it this is specific to the default repository setup on the full install? Can you provide an example of what those files look like? In the most recent docker image `tumbleweed init` works as expected.

**Comment by itaranto** [comment]
I'm sorry but I'm no longer using openSUSE :(
If you can't reproduce it, I think you can close this. Thanks.

**Comment by boombatower** [comment]
Hmm, alright.
