### ISSUE TITLE
System hangs after switching to 20200128

### ISSUE THREAD

**Issue by ulfi** [boombatower/tumbleweed-cli#14]
Starting condition - yast2 nis_server crashes with Snapshoot 20200201 till 20200209
To evaluate the background there was in the [opensuse-factory] mailing list to switch back via tumbleweed-cli. 
So  I do the following steps:
# zypper in tumbleweed-cli
# tumbleweed init
backup /etc/zypp/repos.d/download.opensuse.org-non-oss.repo
backup /etc/zypp/repos.d/download.opensuse.org-oss.repo
# tumbleweed status
latest   : 20200207
target   : 20200207
installed: 20200207
# tumbleweed list
20200209
20200207
20200205
20200201
20200128
[...]
20200110
# tumbleweed switch --install 20200128
[message like ... switch from 20200209 to 20200128 ...]
[installation starts ... after finishing reboot was requested]
# reboot

After reboot, I would check the topic with 
# yast2 nis_server
crashes directly (segmentation fault ...). I would restroe the old etc from 20200129 - but 
# tar -xzf etc20200129.tgz 
crashes also with segmentation fault. So I would l
# ls -l /etc
crashes with segmentation fault :-)

Now I started
# tumbleweed update
system hangs w/o action about 8h
# tumbleweed switch --install 20200209
system hangs w/o action about 8h

I'm not sure if it an issue of the tool or of the repositories (due to update from /etc to /usr/etc at 20200201).

**Comment by boombatower** [comment]
You will have better luck filing this on yast as this project is merely for the tumbleweed CLI tool and not the openSUSE Tumbleweed distribution.
