### ISSUE TITLE
Incorrect switch?

### ISSUE THREAD

**Issue by royyhlee** [boombatower/tumbleweed-cli#15]
Hello, I've been trying to switch install to a specific snapshot by `tumbleweed switch 20200218 --install` but I think it's pointing to the latest. What am I doing wrong?
```
➜  tumbleweed status
latest   : 20200222
target   : 20200127
installed: 20200127
➜  tumbleweed switch 20200218 --install
```

```
The following product is going to be upgraded:
  openSUSE Tumbleweed  20200127-0 -> 20200222-0
```

**Comment by fridlmue** [comment]
As i've learned on Reddit this seems to be your Repository configuration, not a Bug of tw-cli.
[https://www.reddit.com/r/openSUSE/comments/fvhyp2/tumbleweed_cli_output_vs_zypper_output/](https://www.reddit.com/r/openSUSE/comments/fvhyp2/tumbleweed_cli_output_vs_zypper_output/)
