### ISSUE TITLE
Review site has stopped updating

### ISSUE THREAD

**Issue by tvarsis** [boombatower/tumbleweed-cli#18]
Running `tumbleweed status` shows that latest snapshot is 20201114, but on [Review Boombatower](https://review.tumbleweed.boombatower.com/) the latest is 20201108 which seems to have stopped updating. I read something about changes to mail list performed at that day, so maybe there is an update needed to handle that change?

**Comment by boombatower** [comment]
https://github.com/boombatower/tumbleweed-review/issues/9
