### ISSUE TITLE
tumbleweed-cli stoped working at 2020-11-08

### ISSUE THREAD

**Issue by marozsas** [boombatower/tumbleweed-cli#19]
There is any hope to tumbleweed-cli get back in the business or it is dead for good ?
I didn't see any news, any report, any "official" comments on this issue, so I suppose there is no maintainers working on tumbleweed-cli, am I right ?

**Comment by kdejaeger** [comment]
I miss using https://review.tumbleweed.boombatower.com/ !

**Comment by beatgammit** [comment]
It's working fine for me, so I guess it was fixed?

**Comment by kdejaeger** [comment]
Yes indeed

Koen De Jaeger
Mobile : (+31) (0) 6 50454400

**Comment by marozsas** [comment]
Yes, it was, a few weeks later. Something related to a change in the source
that break the process of gathering information.

Miguel Rozsas

Em sáb, 20 de fev de 2021 07:05, Jameson Little <notifications@github.com>
escreveu:

**Comment by kdejaeger** [comment]
I love using it. I use it once every 2/3 months when on a most stable
kernel version.

Koen De Jaeger
Mobile : (+31) (0) 6 50454400

**Comment by boombatower** [comment]
Assume we are talking about the review site? https://github.com/boombatower/tumbleweed-review
