### ISSUE TITLE
Being recommended to remove tumbleweed-cli from the 'revamped' docs: What is your side of the argument?

### ISSUE THREAD

**Issue by why-not-try-calmer** [boombatower/tumbleweed-cli#26]
As a volunteer of the "revamped" Tumbleweed-centric I have received some warnings about tumbleweed-cli: https://github.com/openSUSE/openSUSE-docs-revamped-temp/issues/17.

The heart of the argument displayed there (see also the reddit thread) seems to be that rolling back cuts the user off emergency security patches targeting the latest snapshot. 

What is you side of the argument? Feel free to reply here on in the Issue I referenced above.

**Comment by boombatower** [comment]
I responded https://github.com/openSUSE/openSUSE-docs-revamped-temp/issues/17#issuecomment-897308451.
