### ISSUE TITLE
Tumbleweed Reporting Wrong Snapshop

### ISSUE THREAD

**Issue by ansraliant** [boombatower/tumbleweed-cli#7]
The command `tumbleweed status` reports my installed version is behind the latest available snapshot
```
$ tumbleweed status
latest   : 20180615
target   : 20180615
installed: 20180606
```

However when doing `tumbleweed update` the result is
```
$ tumbleweed update
choosing latest version
already on 20180615
```

I checked `/var/log` for some errors, but found no logs. Also checked `journalctl` and no logs. 

##How to replicate
It happened when an updated was interrupted. 
It would seem that interrupting a download caused this. It's the only thing I remember.

By forcing it, the problem seemed to be solved.
I opened the issue just to let you guys know about the existence of it. 
Feel free to close and leave it there in the backlog. It might help someone one day searching for something similar.

Cheers.

**Comment by boombatower** [comment]
> latest   : 20180615
> target   : 20180615

Are identical. `tumbleweed update` = `tumbleweed switch --install` the switch part tries to change to _latest_ if no snapshot is specified. In this case _target_ = _latest_ so there is no change.

_Target_ refers to what snapshot your zypper repositories point at vs _installed_ is what is actually installed on the system. Just like if you `zypper ref` a couple days after last update you are now pointing at a newer snapshot, but until you `zypper dup` it is not installed.

As such you simply run `zypper dup` like normal. Did it fail when you ran `tumbleweed update` before? If you prefer to manage more directly you can do `tumbleweed switch ; zypper ref ; zypper dup`.

**Comment by boombatower** [comment]
> It happened when an updated was interrupted.

Yes, I missed this before. That is expect as two steps changing what URL your repo points to via the `snapshotVersion` variable and then the `zypper dup`.

**Comment by boombatower** [comment]
Thanks for filing. Feel free to start a FAQ page or somesuch in wiki.

I'll close this since as far as I can understand it works as expected.
