### ISSUE TITLE
Target repositories not available when a new snapshots is "latest"

### ISSUE THREAD

**Issue by binary-sequence** [boombatower/tumbleweed-cli#8]
```bash
sergio@linux-vrhf:~> sudo zypper ref
[sudo] password for sergio: 
Repository 'devel-openQA' is up to date.                                                                                      
Repository 'software-for-life' is up to date.                                                                                 
File '/repodata/repomd.xml' not found on medium 'http://download.tumbleweed.boombatower.com/20180613/repo/non-oss/'
Abort, retry, ignore? [a/r/i/...? shows all options] (a): a
ABORT request: Aborting requested by user

sergio@linux-vrhf:~> tumbleweed status
latest   : 20180618
target   : 20180613
installed: 20180613
```

- 404: http://download.tumbleweed.boombatower.com/20180613/repo/non-oss/
- 200: http://download.tumbleweed.boombatower.com/20180618/repo/non-oss/

**Comment by boombatower** [comment]
There are no indexes so directories are not served. As you can see on the [review site](http://review.tumbleweed.boombatower.com/) `20180613` was never snapshotted although it may have been included in meta and show up as latest. Machine doing snapshots lost network for a bit there.

`20180618` works for me as well.

```
# curl -vL http://download.tumbleweed.boombatower.com/20180618/repo/non-oss/media.1/media
*   Trying 13.33.227.45...
* TCP_NODELAY set
* Connected to download.tumbleweed.boombatower.com (13.33.227.45) port 80 (#0)
> GET /20180618/repo/non-oss/media.1/media HTTP/1.1
> Host: download.tumbleweed.boombatower.com
> User-Agent: curl/7.60.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: binary/octet-stream
< Content-Length: 117
< Connection: keep-alive
< Date: Fri, 22 Jun 2018 19:15:49 GMT
< Last-Modified: Tue, 19 Jun 2018 20:16:34 GMT
< ETag: "1b4bb69fe4c1bb1607ec953068b9e108"
< Server: AmazonS3
< X-Cache: Miss from cloudfront
< Via: 1.1 28ad89a0afe451cfd962b69b8620e893.cloudfront.net (CloudFront)
< X-Amz-Cf-Id: -aeWyUa2dZJ-UvZY4NleLALaHKzLcTnoMkX4Dh-BSHi4lVmcxuDEtQ==
< 
openSUSE - openSUSE-Addon-NonOss-FTP-i586-x86_64-Build279.1-Media
openSUSE-Addon-NonOss-FTP-i586-x86_64-Build279.1
1
* Connection #0 to host download.tumbleweed.boombatower.com left intact
```

I can also access older ones:

```
# curl -L http://download.tumbleweed.boombatower.com/20180615/repo/non-oss/media.1/media
openSUSE - openSUSE-Addon-NonOss-FTP-i586-x86_64-Build275.2-Media
openSUSE-Addon-NonOss-FTP-i586-x86_64-Build275.2
1
```

```
# curl -L http://download.tumbleweed.boombatower.com/20180606/repo/non-oss/media.1/media
openSUSE - openSUSE-Addon-NonOss-FTP-i586-x86_64-Build261.1-Media
openSUSE-Addon-NonOss-FTP-i586-x86_64-Build261.1
1
```

I can even see that the release package is correct date:

```
# curl -sL http://download.tumbleweed.boombatower.com/20180615/rpm.list | grep openSUSE-release-2018
repo/oss/i586/openSUSE-release-20180615-275.1.i586.rpm
repo/oss/x86_64/openSUSE-release-20180615-275.1.x86_64.rpm
```

Assuming then that you updated to `20180613` and happened to get unlucky. :( Let me know if still have issues.

**Comment by boombatower** [comment]
Also note that due to the way the redirect works the latest snapshot will always show as not snapshotted on review site even a day or so after it is replaced. Like `20180618` which is snapshotted, but does not show up that way yet.

**Comment by boombatower** [comment]
Since I believe this was specific to `20180613` not being snapshotted I'll close, but feel free to re-open if still an issue.

**Comment by binary-sequence** [comment]
Thanks for investigating!

Wow, 20180613 was never snapshotted? Which packages did I get when I did ‘tumbleweed update’?

It has happened me three times with the last “showed” snapshots. Since 20180530, I had made three times ‘tumbleweed update’ and I had the same problem. Are the snapshots, even the non-sanapshotted showed in ‘tumbleweed history’? I can send you the list when I get home this evening.

So if this problem means that those snapshots where not published, which packages have I got each time when updating?

**Comment by boombatower** [comment]
The latest snapshot always redirects to main `download.opensuse.org` so you got that snapshot, but if it wasn't saved then nothing left for you to point to once latest changes. I only see the one snapshot missing in that period you mentioned.
